name: Backend CI

on:
  push:
    branches: [main]
    pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: npx prisma generate
        
      - name: Run tests
        run: echo "no tests yet - skipping"

      - name: Docker build
        run: docker build -t saas-backend .